//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Post = new HashSet<Post>();
            this.StoregeRoom = new HashSet<StoregeRoom>();
        }
    
        public int CompanyId { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
        public string WebSite { get; set; }
    
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<StoregeRoom> StoregeRoom { get; set; }
    }
}
