//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoicePosition = new HashSet<InvoicePosition>();
        }
    
        public int IvoiceId { get; set; }
        public int SypplyId { get; set; }
        public System.DateTime DdateInvoice { get; set; }
    
        public virtual Sypply Sypply { get; set; }
        public virtual ICollection<InvoicePosition> InvoicePosition { get; set; }
    }
}
