//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBuyer
    {
        public OrderBuyer()
        {
            this.PositionOrderBuyer = new HashSet<PositionOrderBuyer>();
        }
    
        public int OrderId { get; set; }
        public int BuyerId { get; set; }
        public decimal OrderCost { get; set; }
        public decimal Discount { get; set; }
        public decimal CostWitchDiscond { get; set; }
        public System.DateTime DataOfOrder { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual ICollection<PositionOrderBuyer> PositionOrderBuyer { get; set; }
    }
}
